### PR TITLE
shebang option as a function

### PR DESCRIPTION
**Pull request by manferlo81**
Very simple plugin (which I love), unfortunately for my use case I need to get the shebang string in run time as I extracted from the file before bundling using `rollup-plugin-strip-shebang`, please have a look and merge if you like it. Any other suggestion just let me know. Thanks.

### CODE REVIEW

**Comment by LukasHechenberger** [comment]
Thanks a lot, @manferlo81!

Please note that I merged into a separate branch to ensure CircleCI passes before merging to master.

**Comment by LukasHechenberger** [comment]
Released in v0.3.0

**Comment by manferlo81** [comment]
Thanks a lot. I am sorry if I cause any trouble with the way I submitted the PR, I am kind of new in the GitHub & PR World, hehe. By the way FYI `rollup-pluginutils` changed to typescript and already published their own type definitions, so you don't need to write your own anymore. Success bro!

**Comment by LukasHechenberger** [comment]
Easy ;) Thanks for the tip on `rollup-pluginutils`, I'll have a look on that as well!

**Pull request merged**
